### ISSUE TITLE
Possibility to make some dependencies optional?

### ISSUE THREAD

**Issue by evert** [PHPFastCGI/FastCGIDaemon#21]
Hi!

I'm just taking a look this project, and I think it's extremely interesting. I always thought it was a possibility to do something like this, and now finally somebody has done it. Could be a revolution =)

My main request: the following dependencies could be considered optional:
- psr/http-message
- zendframework/zend-diactoros
- symfony/http-foundation

These dependencies create bit of a dependency graph, but really you only need one of those depending on which http request/response library you'd want to use. Would it be a possibility to make those deps `require-dev` and `suggests`, so if somebody uses PSR-7, they don't _also_ need to include `symfony/http-foundation` ?

**Comment by AndrewCarterUK** [comment]
Thanks very much for your feedback and suggestions :)

Making them require-dev/suggests is one option. However, I think this could be an opportunity to do a bit of a refactor.

The solution I'm learning towards at the moment is creating separate packages: `phpfastcgi/http-foundation-factory` and `phpfastcgi/psr7-factory`.

These packages could contain a factory routine for creating the different request objects so that instead of:

```php
$psr7Request = $request->getServerRequest();
$symfonyRequest = $request->getHttpFoundationRequest();
```

We had:

```php
use PHPFastCGI\Factory\Psr7\Psr7Factory;
use PHPFastCGI\Factory\HttpFoundation\HttpFoundationFactory;

$psr7Request = Psr7Factory::create($request);
$symfonyRequest = HttpFoundationFactory::create($request);
```

I'm toying a bit with syntax here. These methods would be stateless, so there would be no harm in making them static. That said, static behaviour is something I'm trying to get users to avoid relying on (given the context) - so it sets a bit of a counter example.

It wouldn't be any effort (on my part) to just drop the static and require the user to instantiate the factory normally, but it adds a bit of a layer of complexity to the README example that I feel might push some users away:

```php
<?php

require_once dirname(__FILE__) . '/../vendor/autoload.php';

use PHPFastCGI\Factory\Psr7\Psr7Factory;
use PHPFastCGI\FastCGIDaemon\ApplicationFactory;
use PHPFastCGI\FastCGIDaemon\Http\RequestInterface;
use Zend\Diactoros\Response\HtmlResponse;

$psr7Factory = new Psr7Factory();

$kernel = function (RequestInterface $request) use ($psr7Factory) {
    $psr7Request = $psr7Factory->create($request);

    // ...

    return new HtmlResponse('<h1>Hello, World!</h1>');
};

$application = (new ApplicationFactory)->createApplication($kernel);

$application->run();
```

Or I could just do what you suggested and use `require-dev` and `suggests`!

Any thoughts before I go charging away?

**Comment by evert** [comment]
Another possibility is different KernelInterfaces for the different providers. This way you can still abstract this stuff fairly well. OR: different 'Application' classes for each, so you can still allow people to just specify a callback. Personally I found that the hard dependency on the symfony console stuff also added quite a few layers of indirection, and would have personally preferred to have been responsible myself for:

1. Setting up the Deamon object, with all the relevant settings.
2. Hook that object into the Symfony console stuff, optionally... So I can also easily skip that part and use a different approach to configuring my deamon.

Could use a bit more loose coupling imho =)
